FLAGS_PYTHON='-enable-write18'

latex-python-example:
	pdflatex $(FLAGS_PYTHON) latex-python-example

clean:
	rm *~ *.lof *.log *.lot *.aux *.toc *.dvi *.out *.bbl *.blg *.idx *.ilg *.ind *.py* *.png
